// One-off evidence capture for AI Health Summary (Section 19) and Vet Discovery (Section 14).
// Headless Puppeteer: login via REST, inject session cookie, drive the real dashboard UI.
const puppeteer = require('puppeteer');

const BASE = 'http://localhost:3000';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function loginCookie() {
  const res = await fetch(`${BASE}/api/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email: 'owner@example.com', password: 'OwnerPass123!' }),
  });
  if (!res.ok) throw new Error(`Login failed: ${res.status}`);
  const pair = res.headers.get('set-cookie').split(';')[0];
  const idx = pair.indexOf('=');
  return { name: pair.slice(0, idx), value: pair.slice(idx + 1) };
}

async function waitForText(page, text, timeout = 60000) {
  await page.waitForFunction((t) => document.body.innerText.includes(t), { timeout }, text);
  console.log(`  [ok] text present: "${text}"`);
}

async function clickByText(page, selector, text) {
  const clicked = await page.evaluate((sel, txt) => {
    const el = Array.from(document.querySelectorAll(sel)).find((e) => e.textContent.includes(txt));
    if (el) { el.click(); return true; }
    return false;
  }, selector, text);
  if (!clicked) throw new Error(`No ${selector} with text "${text}"`);
  console.log(`  [ok] clicked ${selector}: "${text}"`);
}

async function clickPetByName(page, name) {
  const ok = await page.evaluate((petName) => {
    const h4 = Array.from(document.querySelectorAll('h4')).find((h) => h.textContent.trim() === petName);
    if (!h4) return false;
    let el = h4.parentElement;
    while (el && el !== document.body) {
      if (el.tagName === 'BUTTON' || (el.tagName === 'DIV' && el.className.includes('cursor-pointer'))) {
        el.click();
        return true;
      }
      el = el.parentElement;
    }
    return false;
  }, name);
  if (!ok) throw new Error(`Pet card not found: ${name}`);
  console.log(`  [ok] selected pet: ${name}`);
}

(async () => {
  const cookie = await loginCookie();
  console.log(`Logged in as owner (cookie: ${cookie.name})`);

  const browser = await puppeteer.launch({ headless: true, args: ['--no-sandbox'] });
  const page = await browser.newPage();
  await page.setViewport({ width: 1440, height: 1000, deviceScaleFactor: 1.5 });
  await page.setCookie({ name: cookie.name, value: cookie.value, domain: 'localhost', path: '/' });

  await page.goto(`${BASE}/dashboard`, { waitUntil: 'networkidle2', timeout: 90000 });
  await waitForText(page, 'My Pets', 30000);

  // ---------- Evidence 20: AI Health Summary (Section 19) ----------
  console.log('\n=== Evidence 20: AI Health Summary ===');
  await clickByText(page, 'button', 'My Pets');
  await waitForText(page, 'My Pets Portfolio');
  await clickPetByName(page, 'Milo');
  await waitForText(page, 'AI Health Summary');
  await clickByText(page, 'button', 'Generate Summary');
  console.log('  Waiting for the AI interpretation (provider call, ~10s)...');
  await waitForText(page, 'AI-Generated Interpretation', 120000);
  await waitForText(page, 'Suggested Topics to Discuss with the Vet');
  await waitForText(page, 'Stored Health Facts');

  const summaryCard = await page.evaluateHandle(() => {
    const h5 = Array.from(document.querySelectorAll('h5')).find((h) => h.textContent.includes('AI Health Summary'));
    return h5 ? h5.closest('div.rounded-2xl') : null;
  });
  await summaryCard.asElement().screenshot({ path: 'evidence-20-ai-health-summary.png' });
  console.log('  [saved] evidence-20-ai-health-summary.png');

  const summaryCheck = await page.evaluate(() => ({
    storedFacts: document.body.innerText.includes('Stored Health Facts'),
    aiLabel: document.body.innerText.includes('AI-Generated Interpretation'),
    notDiagnosis: document.body.innerText.includes('not a diagnosis'),
    provider: (document.body.innerText.match(/Generated by (\w+) on/) || [])[1] || null,
    noEmoji: !/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(document.body.innerText),
  }));
  console.log('  Summary card assertions:', JSON.stringify(summaryCheck));

  // ---------- Evidence 21: Find a Vet tab, auto-loaded list (Section 14) ----------
  console.log('\n=== Evidence 21: Find a Vet (auto-load) ===');
  await clickByText(page, 'button', 'Find a Vet');
  await waitForText(page, 'Find a Veterinarian');
  await waitForText(page, 'Dr. Alice Smith'); // auto-search on first open
  await sleep(600);
  await page.screenshot({ path: 'evidence-21-find-a-vet.png' });
  const vetCount = await page.evaluate(() => document.body.innerText.match(/Dr\. /g)?.length || 0);
  console.log(`  [saved] evidence-21-find-a-vet.png (vet name occurrences on screen section: ${vetCount})`);

  // ---------- Evidence 22: filtered search with availability ----------
  console.log('\n=== Evidence 22: Discovery filters + availability ===');
  const availDate = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Karachi' })
    .format(new Date(Date.now() + 10 * 86400000));
  await page.evaluate((dateStr) => {
    const selects = document.querySelectorAll('form select');
    const specSetter = Object.getOwnPropertyDescriptor(window.HTMLSelectElement.prototype, 'value').set;
    specSetter.call(selects[0], 'Dermatology');
    selects[0].dispatchEvent(new Event('change', { bubbles: true }));
    const dateInput = document.querySelector('form input[type="date"]');
    const inputSetter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value').set;
    inputSetter.call(dateInput, dateStr);
    dateInput.dispatchEvent(new Event('input', { bubbles: true }));
    dateInput.dispatchEvent(new Event('change', { bubbles: true }));
  }, availDate);
  console.log(`  Filters set: specialization=Dermatology, date=${availDate}`);
  await clickByText(page, 'button', 'Search');
  await waitForText(page, 'Free times on');
  await waitForText(page, 'Dr. Diana Prince');
  await sleep(400);
  await page.screenshot({ path: 'evidence-22-discovery-filtered-availability.png' });
  console.log('  [saved] evidence-22-discovery-filtered-availability.png');

  // ---------- Evidence 23: booking modal prefilled from discovery ----------
  console.log('\n=== Evidence 23: Booking modal prefilled from discovery ===');
  await clickByText(page, 'button', 'Book Appointment');
  await waitForText(page, 'Submit Booking');
  const modalCheck = await page.evaluate(() => {
    const vetSelect = Array.from(document.querySelectorAll('select')).find((s) =>
      Array.from(s.options).some((o) => o.textContent.includes('Dr. Diana Prince')));
    const petSelect = Array.from(document.querySelectorAll('select')).find((s) =>
      Array.from(s.options).some((o) => o.textContent === 'Milo'));
    return {
      vetSelected: vetSelect ? vetSelect.options[vetSelect.selectedIndex]?.textContent : null,
      petSelected: petSelect ? petSelect.options[petSelect.selectedIndex]?.textContent : null,
    };
  });
  console.log('  Modal prefill assertions:', JSON.stringify(modalCheck));
  await sleep(300);
  await page.screenshot({ path: 'evidence-23-booking-modal-from-discovery.png' });
  console.log('  [saved] evidence-23-booking-modal-from-discovery.png');

  await browser.close();
  console.log('\nAll evidence captured.');
})().catch((e) => { console.error('FATAL:', e.message); process.exit(1); });
